/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogodavelha21;

/**
 *
 * @author lenovo
 */
import javax.swing.JButton;
import javax.swing.JOptionPane;
public class Principal extends javax.swing.JFrame {
    int qtde;
    int jogador;
    int mat[][] = new int [3][3];
    JButton b[] = new JButton[9];
    String ganhador;
    String jogador1;
    String jogador2;

    /**
     * Creates new form JogodaVelha21
     */
    public Principal() 
    {
        initComponents();
        qtde = 1;
        jogador = 1;
        b[0] = but_1;
        b[1] = but_2;
        b[2] = but_3;
        b[3] = but_4;
        b[4] = but_5;
        b[5] = but_6;
        b[6] = but_7;
        b[7] = but_8;
        b[8] = but_9;
    }
    
    public void checarjogada(int x)
    {
        if(vitoria(x) == true)
        {
            JOptionPane.showMessageDialog(null, "Jogador: " + ganhador + " " + "Venceu! ", "Vitória", JOptionPane.INFORMATION_MESSAGE);
            fimjogo();
        }
    }
    
    public boolean vitoria(int x)
    {
        for(int i = 0; i < mat.length; i++) 
        {
            if(mat[i][0] == x && mat[i][1] == x && mat[i][2] == x) 
            {
                return true;
            }
            if(mat[0][i] == x && mat[1][i] == x && mat[2][i] == x)
            {
                return true;
            }
        }
        if(mat[0][0] == x && mat[1][1] == x && mat[2][2] == x)
        {
            return true;
        }
        if(mat[0][2] == x && mat[1][1] == x && mat[2][0] == x)
        {
            return true;
        }
        return false;
    }
    
    public void fimjogo()
    {
        for(int i = 0; i < 9; i++)
        {
            b[i].setEnabled(false);
        }
    }
    
     public void jogada(JButton b, int x, int y)
    {
        b.setEnabled(false);
        if(jogador == 1)
        {
            mat[x][y] = 1;
            b.setText("X");
            jogador = 2;
            ganhador = jogador1;
            checarjogada(1);
        }
        else
        {
            mat[x][y] = 2;
            b.setText("O");
            jogador = 1;
            ganhador = jogador2;
            checarjogada(2);
        }
        qtde++;
    }
     
     public void limpar()
    {
        for(int i = 0; i < 9; i++)
        {
            b[i].setEnabled(true);
            b[i].setText("");
        }
        for(int x = 0; x < 3; x++)
        {
            for(int y = 0; y < 3; y++)
            {
                mat[x][y] = 0;
            }
        }
        jogador = 1;
        jogador1 = "";
        jogador2 = "";
        ganhador = "";
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but_1 = new javax.swing.JButton();
        but_2 = new javax.swing.JButton();
        but_3 = new javax.swing.JButton();
        but_4 = new javax.swing.JButton();
        but_5 = new javax.swing.JButton();
        but_6 = new javax.swing.JButton();
        but_7 = new javax.swing.JButton();
        but_8 = new javax.swing.JButton();
        but_9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 237, 245));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.blue);
        setPreferredSize(new java.awt.Dimension(400, 400));

        but_1.setBackground(new java.awt.Color(8, 11, 1));
        but_1.setForeground(new java.awt.Color(2, 4, 98));
        but_1.setEnabled(false);
        but_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_1ActionPerformed(evt);
            }
        });

        but_2.setBackground(new java.awt.Color(8, 11, 1));
        but_2.setForeground(new java.awt.Color(2, 4, 98));
        but_2.setEnabled(false);
        but_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_2ActionPerformed(evt);
            }
        });

        but_3.setBackground(new java.awt.Color(8, 11, 1));
        but_3.setForeground(new java.awt.Color(2, 4, 98));
        but_3.setEnabled(false);
        but_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_3ActionPerformed(evt);
            }
        });

        but_4.setBackground(new java.awt.Color(8, 11, 1));
        but_4.setForeground(new java.awt.Color(2, 4, 98));
        but_4.setEnabled(false);
        but_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_4ActionPerformed(evt);
            }
        });

        but_5.setBackground(new java.awt.Color(8, 11, 1));
        but_5.setForeground(new java.awt.Color(2, 4, 98));
        but_5.setEnabled(false);
        but_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_5ActionPerformed(evt);
            }
        });

        but_6.setBackground(new java.awt.Color(8, 11, 1));
        but_6.setForeground(new java.awt.Color(2, 4, 98));
        but_6.setEnabled(false);
        but_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_6ActionPerformed(evt);
            }
        });

        but_7.setBackground(new java.awt.Color(8, 11, 1));
        but_7.setForeground(new java.awt.Color(2, 4, 98));
        but_7.setEnabled(false);
        but_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_7ActionPerformed(evt);
            }
        });

        but_8.setBackground(new java.awt.Color(8, 11, 1));
        but_8.setForeground(new java.awt.Color(2, 4, 98));
        but_8.setEnabled(false);
        but_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_8ActionPerformed(evt);
            }
        });

        but_9.setBackground(new java.awt.Color(8, 11, 1));
        but_9.setForeground(new java.awt.Color(2, 4, 98));
        but_9.setEnabled(false);
        but_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_9ActionPerformed(evt);
            }
        });

        jMenu1.setText("Opção");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setMnemonic('N');
        jMenuItem1.setText("Novo Jogo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(but_7, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(but_8, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(but_9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(but_6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(but_3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but_5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addComponent(but_6, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(but_7, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(but_8, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_8ActionPerformed
        // TODO add your handling code here:
        jogada(but_8, 2, 1);
    }//GEN-LAST:event_but_8ActionPerformed

    private void but_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_1ActionPerformed
        jogada(but_1,0, 0);
    }//GEN-LAST:event_but_1ActionPerformed

    private void but_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_2ActionPerformed
        // TODO add your handling code here:
        jogada(but_2, 0, 1);
    }//GEN-LAST:event_but_2ActionPerformed

    private void but_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_3ActionPerformed
        // TODO add your handling code here:
        jogada(but_3, 0, 2);
    }//GEN-LAST:event_but_3ActionPerformed

    private void but_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_4ActionPerformed
        // TODO add your handling code here:
        jogada(but_4, 1, 0);
    }//GEN-LAST:event_but_4ActionPerformed

    private void but_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_5ActionPerformed
        // TODO add your handling code here:
        jogada(but_5, 1, 1);
    }//GEN-LAST:event_but_5ActionPerformed

    private void but_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_6ActionPerformed
        // TODO add your handling code here:
        jogada(but_6, 1, 2);
    }//GEN-LAST:event_but_6ActionPerformed

    private void but_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_7ActionPerformed
        // TODO add your handling code here:
        jogada(but_7, 2, 0);
    }//GEN-LAST:event_but_7ActionPerformed

    private void but_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_9ActionPerformed
        // TODO add your handling code here:
        jogada(but_9, 2, 2);
    }//GEN-LAST:event_but_9ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        limpar();
        jogador1 = JOptionPane.showInputDialog("Digite o Nome do Primeiro Jogador:");
        jogador2 = JOptionPane.showInputDialog("Digite o Nome do Segundo Jogador:");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_1;
    private javax.swing.JButton but_2;
    private javax.swing.JButton but_3;
    private javax.swing.JButton but_4;
    private javax.swing.JButton but_5;
    private javax.swing.JButton but_6;
    private javax.swing.JButton but_7;
    private javax.swing.JButton but_8;
    private javax.swing.JButton but_9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
